version: '3.8'
services:

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: ${db_password}
            POSTGRES_DB: ${db_name}
        ports:
          - 5432:5432
        volumes:
          - data:/var/lib/postgresql

    bot:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - ./.env
        command: >
            sh -c "alembic upgrade head && python main.py"
        depends_on:
            - postgres

volumes:
  data: