"""New_role_admin

Revision ID: 072f2b7f57cf
Revises: 13601d248abe
Create Date: 2023-09-19 02:24:27.584384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072f2b7f57cf'
down_revision = '13601d248abe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.create_foreign_key(None, 'users', 'users', ['admin_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'admin_id')
    # ### end Alembic commands ###
