"""New_role_admin_2.0

Revision ID: 3bad2d213b75
Revises: 771630f9b583
Create Date: 2023-09-19 02:43:52.604695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bad2d213b75'
down_revision = '771630f9b583'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
