"""Initial

Revision ID: 53e791fec308
Revises: d683d98c4f1c
Create Date: 2023-09-11 12:12:41.204970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e791fec308'
down_revision = 'd683d98c4f1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coach_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['coach_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'coach_id')
    # ### end Alembic commands ###
