"""New_role_admin_1.0

Revision ID: 771630f9b583
Revises: 072f2b7f57cf
Create Date: 2023-09-19 02:39:27.982103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771630f9b583'
down_revision = '072f2b7f57cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
