"""add_type_hw

Revision ID: 91d5adaddf4b
Revises: b1a05c3d6989
Create Date: 2023-10-11 11:43:31.246409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91d5adaddf4b'
down_revision = 'b1a05c3d6989'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('data', postgresql.BYTEA(), nullable=True))
    op.add_column('homeworks', sa.Column('type_data', sa.Integer(), nullable=False))
    op.drop_column('homeworks', 'photo')
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('homeworks', sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('homeworks', 'type_data')
    op.drop_column('homeworks', 'data')
    # ### end Alembic commands ###
