"""add_records

Revision ID: aa0e99c5d948
Revises: 91d5adaddf4b
Create Date: 2023-10-16 11:31:57.997703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa0e99c5d948'
down_revision = '91d5adaddf4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('student_id', sa.BigInteger(), nullable=True),
    sa.Column('topic', sa.VARCHAR(length=50), nullable=True),
    sa.Column('data', postgresql.BYTEA(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
